### ISSUE TITLE
Illegal Argument Exception on preview-job endpoint

### ISSUE THREAD

**Issue by nelsonw2014** [commercehub-oss/watershed#65]
When executing the preview-job command on the client, the server has an IllegalArgumentException, citing parameter bucketName was not provided.

```
ERROR [2016-01-08 17:25:02,583] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 0429d427bb621131
! org.apache.drill.common.exceptions.UserRemoteException: SYSTEM ERROR: IllegalArgumentException: The bucketName parameter must be specified.
! 
! 
! [Error Id: <ID> on <IP>:31010]
! at org.apache.drill.exec.rpc.user.QueryResultHandler.resultArrived(QueryResultHandler.java:118) ~[na:na]
! at org.apache.drill.exec.rpc.user.UserClient.handleReponse(UserClient.java:111) ~[na:na]
! at org.apache.drill.exec.rpc.BasicClientWithConnection.handle(BasicClientWithConnection.java:47) ~[na:na]
! at org.apache.drill.exec.rpc.BasicClientWithConnection.handle(BasicClientWithConnection.java:32) ~[na:na]
! at org.apache.drill.exec.rpc.RpcBus.handle(RpcBus.java:61) ~[na:na]
! at org.apache.drill.exec.rpc.RpcBus$InboundHandler.decode(RpcBus.java:233) ~[na:na]
! at org.apache.drill.exec.rpc.RpcBus$InboundHandler.decode(RpcBus.java:205) ~[na:na]
! at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[na:na]
! at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[na:na]
! at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[na:na]
! at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[na:na]
! at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) ~[na:na]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) ~[na:na]
! at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847) ~[na:na]
! at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[na:na]
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[na:na]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[na:na]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[na:na]
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[na:na]
! at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) ~[na:na]
! ... 1 common frames omitted
! Causing: java.sql.SQLException: SYSTEM ERROR: IllegalArgumentException: The bucketName parameter must be specified.
! 
! 
! [Error Id: <ID> on <IP>:31010]
! at org.apache.drill.jdbc.impl.DrillCursor.nextRowInternally(DrillCursor.java:214) ~[na:na]
! at org.apache.drill.jdbc.impl.DrillCursor.loadInitialSchema(DrillCursor.java:257) ~[na:na]
! at org.apache.drill.jdbc.impl.DrillResultSetImpl.execute(DrillResultSetImpl.java:1362) ~[na:na]
! at org.apache.drill.jdbc.impl.DrillResultSetImpl.execute(DrillResultSetImpl.java:72) ~[na:na]
! at net.hydromatic.avatica.AvaticaConnection.executeQueryInternal(AvaticaConnection.java:404) ~[na:na]
! at net.hydromatic.avatica.AvaticaStatement.executeQueryInternal(AvaticaStatement.java:351) ~[na:na]
! at net.hydromatic.avatica.AvaticaStatement.executeQuery(AvaticaStatement.java:78) ~[na:na]
! at org.apache.drill.jdbc.impl.DrillStatementImpl.executeQuery(DrillStatementImpl.java:96) ~[na:na]
! at com.commercehub.watershed.pump.respositories.DrillRepository.getJobPreview(DrillRepository.java:37) ~[watershed-pump-0.1.0.shadow.jar:na]
! at com.commercehub.watershed.pump.service.JobServiceImpl.getJobPreview(JobServiceImpl.java:71) ~[watershed-pump-0.1.0.shadow.jar:na]
! at com.commercehub.watershed.pump.resources.PumpResource.previewJob(PumpResource.java:91) ~[watershed-pump-0.1.0.shadow.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_76]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_76]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_76]
! at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_76]
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308) ~[watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [watershed-pump-0.1.0.shadow.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [watershed-pump-0.1.0.shadow.jar:na]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [watershed-pump-0.1.0.shadow.jar:na]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [watershed-pump-0.1.0.shadow.jar:na]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [watershed-pump-0.1.0.shadow.jar:na]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) [watershed-pump-0.1.0.shadow.jar:na]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [watershed-pump-0.1.0.shadow.jar:na]
! at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89) [watershed-pump-0.1.0.shadow.jar:na]
! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) [watershed-pump-0.1.0.shadow.jar:na]
! at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) [watershed-pump-0.1.0.shadow.jar:na]
! at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) [watershed-pump-0.1.0.shadow.jar:na]
! at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) [watershed-pump-0.1.0.shadow.jar:na]
! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [watershed-pump-0.1.0.shadow.jar:na]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [watershed-pump-0.1.0.shadow.jar:na]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.Server.handle(Server.java:497) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [watershed-pump-0.1.0.shadow.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [watershed-pump-0.1.0.shadow.jar:na]
! at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]
```

**Comment by nelsonw2014** [comment]
Errors on create-job as well

**Comment by CrossfireCurt** [comment]
This is because the S3 URL is not encoded. Spoke to @nelsonw2014 over HipChat regarding it - had to encode forward slash to be "%2F"
